name: Build and Test Calculator
on: [pull_request, push]
env:
  BUILD_TYPE: Release
jobs:
  calculator:
    name: "GAMES101"
    runs-on: ubuntu-latest
    env:
      SRC_PATH: ${{github.workspace}}
      BUILD_PATH: ${{github.workspace}}/build
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        working-directory: ${{env.SRC_PATH}}
        run: cmake -B ${{env.BUILD_PATH}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        env:
          CXX: g++
          CC: gcc
      - name: Build
        working-directory: ${{env.SRC_PATH}}
        run: cmake --build ${{env.BUILD_PATH}} --config ${{env.BUILD_TYPE}}
